#!/usr/bin/env bash
# scripts/deploy-production.sh
# One-click production deployment for CNC mainnet + web publish.

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env"
OUTPUT_DIR="$PROJECT_ROOT/deploy/output"
LOG_DIR="$PROJECT_ROOT/deploy/logs"

SKIP_CHAIN="false"
SKIP_WEB="false"
WRITE_ENV="true"

usage() {
  cat <<'EOF'
Usage: bash scripts/deploy-production.sh [options]

Options:
  --skip-chain   Skip contract deployment, deploy web only
  --skip-web     Skip web deployment, deploy contracts only
  --no-write-env Do not sync deployed addresses back into .env
  -h, --help     Show this help

Examples:
  npm run deploy:prod
  npm run deploy:prod -- --skip-chain
  npm run deploy:prod -- --skip-web
EOF
}

for arg in "$@"; do
  case "$arg" in
    --skip-chain)
      SKIP_CHAIN="true"
      ;;
    --skip-web)
      SKIP_WEB="true"
      ;;
    --no-write-env)
      WRITE_ENV="false"
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $arg"
      usage
      exit 1
      ;;
  esac
done

cd "$PROJECT_ROOT"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing .env file. Create it first: cp .env.example .env"
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

mkdir -p "$OUTPUT_DIR" "$LOG_DIR"

timestamp="$(date +%Y%m%d-%H%M%S)"
deploy_log="$LOG_DIR/chain-deploy-$timestamp.log"
latest_env="$OUTPUT_DIR/latest-addresses.env"

require_env() {
  local key="$1"
  if [[ -z "${!key:-}" ]]; then
    echo "Missing required env: $key"
    return 1
  fi
  return 0
}

update_env_key() {
  local key="$1"
  local value="$2"

  if grep -qE "^${key}=" "$ENV_FILE"; then
    sed -i "s|^${key}=.*|${key}=${value}|" "$ENV_FILE"
  else
    echo "${key}=${value}" >> "$ENV_FILE"
  fi
}

extract_address() {
  local label="$1"
  local line
  line="$(grep -E "^${label}:" "$deploy_log" | tail -n 1 || true)"
  if [[ -z "$line" ]]; then
    echo ""
    return
  fi
  echo "$line" | awk '{print $2}'
}

if [[ "$SKIP_CHAIN" == "false" ]]; then
  echo "==> Validating chain deployment environment"
  require_env "DEPLOYER_PRIVATE_KEY"
  require_env "CNC_MAINNET_RPC_URL"
  require_env "USDT_TOKEN_ADDRESS"

  echo "==> Compiling contracts"
  npm run compile

  echo "==> Deploying contracts to cncMainnet"
  npm run deploy:cncMainnet | tee "$deploy_log"

  usdt_address="$(extract_address "USDT")"
  ico_address="$(extract_address "ICO")"
  light_address="$(extract_address "LIGHT")"
  core_proxy="$(extract_address "IncubatorCore")"
  otc_proxy="$(extract_address "NodeOTCMarket")"
  swap_proxy="$(extract_address "SwapPoolManager")"

  if [[ -z "$core_proxy" || -z "$otc_proxy" || -z "$swap_proxy" ]]; then
    echo "Could not parse deployed contract addresses from $deploy_log"
    exit 1
  fi

  cat > "$latest_env" <<EOF
# Generated by scripts/deploy-production.sh at $timestamp
USDT_TOKEN_ADDRESS=$usdt_address
ICO_TOKEN_ADDRESS=$ico_address
LIGHT_TOKEN_ADDRESS=$light_address
INCUBATOR_CORE_PROXY=$core_proxy
NODE_OTC_MARKET_PROXY=$otc_proxy
SWAP_POOL_MANAGER_PROXY=$swap_proxy

VITE_USDT_CONTRACT_ADDRESS=$usdt_address
VITE_ICO_TOKEN_ADDRESS=$ico_address
VITE_LIGHT_TOKEN_ADDRESS=$light_address
VITE_CORE_CONTRACT_ADDRESS=$core_proxy
VITE_OTC_CONTRACT_ADDRESS=$otc_proxy
VITE_SWAP_POOL_ADDRESS=$swap_proxy
EOF

  echo "==> Wrote deployed addresses: $latest_env"

  if [[ "$WRITE_ENV" == "true" ]]; then
    echo "==> Syncing deployed addresses into .env"
    update_env_key "USDT_TOKEN_ADDRESS" "$usdt_address"
    update_env_key "ICO_TOKEN_ADDRESS" "$ico_address"
    update_env_key "LIGHT_TOKEN_ADDRESS" "$light_address"
    update_env_key "INCUBATOR_CORE_PROXY" "$core_proxy"
    update_env_key "NODE_OTC_MARKET_PROXY" "$otc_proxy"
    update_env_key "SWAP_POOL_MANAGER_PROXY" "$swap_proxy"
    update_env_key "VITE_USDT_CONTRACT_ADDRESS" "$usdt_address"
    update_env_key "VITE_ICO_TOKEN_ADDRESS" "$ico_address"
    update_env_key "VITE_LIGHT_TOKEN_ADDRESS" "$light_address"
    update_env_key "VITE_CORE_CONTRACT_ADDRESS" "$core_proxy"
    update_env_key "VITE_OTC_CONTRACT_ADDRESS" "$otc_proxy"
    update_env_key "VITE_SWAP_POOL_ADDRESS" "$swap_proxy"
  fi
fi

if [[ "$SKIP_WEB" == "false" ]]; then
  if [[ -f "$PROJECT_ROOT/deploy/caddy/deploy.sh" ]]; then
    echo "==> Deploying web via Caddy"
    npm run deploy:caddy
  else
    echo "==> Caddy deploy script not found, building web only"
    npm run build:web
  fi
fi

echo "==> Deployment pipeline completed"
echo "    Chain log: $deploy_log"
echo "    Address file: $latest_env"
